name = "marencore"
main = "worker.js"
compatibility_date = "2026-01-10"

[env.production]
vars = { ENVIRONMENT = "production" }

[build]
command = "npm run build"
cwd = "."

[[build.upload.rules]]
type = "CompiledContentType"
globs = ["dist/**/*"]
fallthrough = true
